version: '3.1'

services:
  tomcat:
    container_name: target-tomcat8.5
    restart: always
    ports:
      - 58080:8080
    build:
      context: .
      dockerfile: target.dockerfile
    image: tomcat:8.5.92-rasp

volumes:
  rasp-target-tomcat8.5:
    driver: local